# Docker Compose settings
version: '2'
services:
    mysql:
        container_name: stud_mysql
        build: ./mysql
        ports:
            - 3308:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/stud.cnf:/etc/mysql/conf.d/stud.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=stud
            - MYSQL_DATABASE=stud_app
            - MYSQL_USER=stud
            - MYSQL_PASSWORD=stud
        restart: always


    nginx:
        container_name: stud_nginx
        build: ./nginx
        volumes:
            - ./phpmyadmin:/var/www/phpmyadmin
            - ./nginx/stud.conf:/etc/nginx/conf.d/stud.conf
            - ./nginx/sites:/etc/nginx/sites-enabled
            - ./nginx/entrypoint.sh:/sbin/entrypoint.sh
        working_dir: /var/www/html
        environment:
            - MADM_DIR=/var/www/phpmyadmin
            - DB_CONT=mysql
        ports:
            - 81:80
            - 444:443
        command: entrypoint.sh
        restart: always


    node:
        container_name: stud_node
        image: node:latest
        volumes:
            - ../stud_front:/app
        working_dir: /app
        ports:
            - 82:8080
        command: sh -c "npm i -q && npm run dev"
        restart: always
